spring:
  application:
    name: display
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true   # true as default in Dalston

server:
  port: 8081

hystrix:
  command:
    productInfo:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000   # default 1,000ms
      circuitBreaker:
        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

product:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082,localhost:7777
    MaxAutoRetries: 0  # default 0
    MaxAutoRetriesNextServer: 1 # default 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address